server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 11111

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.gjb.springcloud.entities #Entity别名实例



eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册金EurekaServer默认为true
    fetch-registry: true       #是否从EurekaServer住区已有的注册信息，默认为true。集群必须设置为true才能配合ribbon的负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka



